spring:
  application: 
    name: Config-default-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/hotel_user
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
     ddl-auto: update
     show-sql: true
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
