spring:
  application: 
    name: Config-default-SERVICE
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
